name: Rust

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Установка Rust
      uses: moonrepo/setup-rust@v1
      with:
        rust-version: stable

    - name: Сборка
      run: cargo build --verbose

    - name: Тестирование
      run: cargo test --verbose
